### ISSUE TITLE
Policy / AGB Button - not clickable

### ISSUE THREAD

**Issue by oneloveworks** [creativelittledots/woocommerce-pay-later#2]
I use the the plugin, but when i go to the orders for later pay then i can not click in the field for policy. it is not possible to check this field.
<img width="433" alt="bildschirmfoto 2016-10-28 um 02 02 16" src="https://cloud.githubusercontent.com/assets/23110189/19789753/a38331ca-9cb2-11e6-82a3-fdb08e81ffa2.png">

**Comment by terence1990** [comment]
Hi There,

It's not possible that the plugin is causing this issue. I am sure if you
disabled Pay Later and enabled Bank Transfer for example you'd still have
this issue - it's a CSS issue in your theme.

Many thanks,

Terence O'DonoghueCreative Little Director

_Email:_ terence@creativelittledots.co.uk
_Phone:_ 01483 802 940 <01483802940>

_Office Hours:_ 9.30am - 5.30pm, Monday - Friday

## _Support:_ support@creativelittledots.co.uk

http://goo.gl/4zs1tr http://goo.gl/wd4foK http://goo.gl/DuQFlM
http://goo.gl/PQ63pS

This email & any attachment is intended for the named contact(s), or any
person authorised to receive it on their behalf so should be treated as
confidential. The recipient may not disclose this message or any attachment
to anyone else without authorisation, doing so may be unlawful. If this
email is received in error please notify the sender urgently & delete this
message from your system. Any view expressed by the sender of this message
or any attachment may be personal & may not represent the view held by
Creative Little Dots. All emails to & from Creative Little Dots are
recorded, may be monitored & scanned for viruses, we accept no liability
for viruses or other material introduced with this message.

Creative Little Dots Ltd   |   Companies House Reg: 9066408   |   Vat
Registration: 188664940
