### ISSUE TITLE
Not Sending Emails

### ISSUE THREAD

**Issue by blushell** [creativelittledots/woocommerce-pay-later#3]
When this plugin is enabled it does not send out woocommerce emails to both the owner and the client ?

**Comment by terence1990** [comment]
Hi,

can you provide a screenshot?

Terence O'DonoghueCreative Little Director

_Email:_ terence@creativelittledots.co.uk
_Phone:_ 01483 802 940 <01483802940>

_Office Hours:_ 9.30am - 5.30pm, Monday - Friday

## _Support:_ support@creativelittledots.co.uk

http://goo.gl/4zs1tr http://goo.gl/wd4foK http://goo.gl/DuQFlM
http://goo.gl/PQ63pS

This email & any attachment is intended for the named contact(s), or any
person authorised to receive it on their behalf so should be treated as
confidential. The recipient may not disclose this message or any attachment
to anyone else without authorisation, doing so may be unlawful. If this
email is received in error please notify the sender urgently & delete this
message from your system. Any view expressed by the sender of this message
or any attachment may be personal & may not represent the view held by
Creative Little Dots. All emails to & from Creative Little Dots are
recorded, may be monitored & scanned for viruses, we accept no liability
for viruses or other material introduced with this message.

Creative Little Dots Ltd   |   Companies House Reg: 9066408   |   Vat
Registration: 188664940

**Comment by terence1990** [comment]
Hi,

My recent commit should fix this issue.

Many thanks,

Terence O'DonoghueCreative Little Director

_Email:_ terence@creativelittledots.co.uk
_Phone:_ 01483 802 940 <01483802940>

_Office Hours:_ 9.30am - 5.30pm, Monday - Friday

## _Support:_ support@creativelittledots.co.uk

http://goo.gl/4zs1tr http://goo.gl/wd4foK http://goo.gl/DuQFlM
http://goo.gl/PQ63pS

This email & any attachment is intended for the named contact(s), or any
person authorised to receive it on their behalf so should be treated as
confidential. The recipient may not disclose this message or any attachment
to anyone else without authorisation, doing so may be unlawful. If this
email is received in error please notify the sender urgently & delete this
message from your system. Any view expressed by the sender of this message
or any attachment may be personal & may not represent the view held by
Creative Little Dots. All emails to & from Creative Little Dots are
recorded, may be monitored & scanned for viruses, we accept no liability
for viruses or other material introduced with this message.

Creative Little Dots Ltd   |   Companies House Reg: 9066408   |   Vat
Registration: 188664940
