### ISSUE TITLE
Is it compatible with woocommerce 3.0?

### ISSUE THREAD

**Issue by sebabal** [creativelittledots/woocommerce-pay-later#4]
I am getting an error whenever trying to apply any action to an order...

`NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to a member function set() on null at wp-content/plugins/woocommerce-pay-later-master/includes/gateways/pay-later/class-wc-gateway-pay-later.php:64`

Any ideas?

**Comment by terence1990** [comment]
Hey @sebabal I have committed a fix for your issue
