### ISSUE TITLE
Warning: Missing argument 2 for WC_Session::set(),

### ISSUE THREAD

**Issue by uakhan** [creativelittledots/woocommerce-pay-later#5]
This error/warning is showing everywhere with order detail.

Warning: Missing argument 2 for WC_Session::set(), called in \wp-content\plugins\woocommerce-pay-later-master\includes\gateways\pay-later\class-wc-gateway-pay-later.php on line 64 and defined in \wp-content\plugins\woocommerce\includes\abstracts\abstract-wc-session.php on line 87

I turned off all the other plugins, still the same result. However, order status certainly changes to "pending-payment".

Woocommerce version: 3.1.2
WP Version: Version 4.8.2

**Comment by terence1990** [comment]
resolved:

https://github.com/creativelittledots/woocommerce-pay-later/pull/7
