### ISSUE TITLE
No emails are triggering

### ISSUE THREAD

**Issue by uakhan** [creativelittledots/woocommerce-pay-later#6]
I believe it has something to do with that error/warning I am getting. I turned off all the other plugins, still the same result. However, order status certainly changes to "pending-payment".

Woocommerce version: 3.1.2
WP Version: Version 4.8.2

**Comment by jeffreydotfong** [comment]
Hi, 

I have the same issue. Gateway works perfectly except for this step. Status is "pending" but customer never receives the "customer invoice" email.

WC 3.1.1
WP 4.9.1

**Comment by terence1990** [comment]
I believe this has been resolved on https://github.com/creativelittledots/woocommerce-pay-later/pull/7 since statuses will now default to on-hold and change to pending which will cause the emails to go out successfully.

Feel free to raise the issue again if you come across it
