### ISSUE TITLE
Email content duplication

### ISSUE THREAD

**Issue by MaxLeven** [creativelittledots/woocommerce-pay-later#8]
I have installed this plugin and test it. All works fine except email content duplication. 
After order admin and user get emails with details that are duplicating content.
Using WordPress 4.9.8, WooCommerce 3.4.5

**Comment by terence1990** [comment]
Hey @MaxLeven,

Do you mean content is duplicating with the email itself, or do you mean you are receiving duplicate emails?

Cheers,

**Comment by MaxLeven** [comment]
Hi, @terence1990. See the screen bellow.
![email ipad](https://user-images.githubusercontent.com/6933203/46997450-677de100-d128-11e8-9b89-4bd7c72f6d1d.png)

**Comment by MaxLeven** [comment]
Hello @terence1990. Any ideas?

**Comment by ctrandafir-tech** [comment]
Am having same issue, any ideas on a fix ? @terence1990 , @matt3224

**Comment by terence1990** [comment]
@MaxLeven @Cristycs I can't recreate this issue, but then I haven't been able test older versions of WC etc.

I would suggest trying to solve it yourselves, forking this repo and raising a PR for the fix yourselves. Happy to merge in any fixes very quickly once they are raised
